### PR TITLE
Updates packages and minimize memory footprint

### PR DESCRIPTION
**Pull request by medanat**
This PR might not work with the current supported Node.js/iojs versions. 

I would like to see the CI tests output.

### CODE REVIEW

**Comment by medanat** [comment]
This fails on Node.js < 4, would like some input from maintainers whether to aim for backwards compatibility or release this a major version with breaking changes.

**Comment by medanat** [comment]
Just as a note, `pm2` only supports Node.js 4+ atm:

https://github.com/Unitech/pm2/blob/master/.travis.yml

**Comment by medanat** [comment]
@vmarchaud This *does* work with Node 4:

https://travis-ci.org/keymetrics/vizion/builds/404950808?utm_source=github_status&utm_medium=notification

Just not with previous versions.

**Comment by vmarchaud** [comment]
Then its totally fine, could you remove older versions and add node 6, 8, 9 and 10 in the CI ? Thanks

**Comment by medanat** [comment]
@vmarchaud sure thing!

**Pull request merged**
